import { ProviderAvailability } from '../types/availability';
import { Patient, Provider, Appointment, AppointmentListItem } from '../types/appointment';

export const sampleAvailabilityData: ProviderAvailability[] = [
  {
    id: 'availability-1',
    providerId: 'current-provider',
    providerName: 'Dr. John Doe',
    dayAvailabilities: [
      {
        id: 'day-1',
        day: 'Monday',
        startTime: '09:00',
        endTime: '17:00',
      },
      {
        id: 'day-2',
        day: 'Tuesday',
        startTime: '09:00',
        endTime: '17:00',
      },
      {
        id: 'day-3',
        day: 'Wednesday',
        startTime: '09:00',
        endTime: '17:00',
      },
      {
        id: 'day-4',
        day: 'Thursday',
        startTime: '09:00',
        endTime: '17:00',
      },
      {
        id: 'day-5',
        day: 'Friday',
        startTime: '09:00',
        endTime: '17:00',
      },
      {
        id: 'day-6',
        day: 'Saturday',
        startTime: '10:00',
        endTime: '14:00',
      },
    ],
    blockDays: [
      {
        id: 'block-1',
        date: '2024-12-25',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 'block-2',
        date: '2024-12-26',
        startTime: '00:00',
        endTime: '23:59',
      },
    ],
    timezone: 'America/New_York',
    repeatWeekly: true,
    locationMode: 'In-clinic',
    notes: 'Available for in-person consultations and virtual appointments.',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];

export const samplePatients: Patient[] = [
  {
    id: 'patient-1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+1-555-0123',
    dateOfBirth: '1985-03-15',
  },
  {
    id: 'patient-2',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+1-555-0124',
    dateOfBirth: '1990-07-22',
  },
  {
    id: 'patient-3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@email.com',
    phone: '+1-555-0125',
    dateOfBirth: '1988-11-08',
  },
  {
    id: 'patient-4',
    name: 'David Thompson',
    email: 'david.thompson@email.com',
    phone: '+1-555-0126',
    dateOfBirth: '1975-05-12',
  },
  {
    id: 'patient-5',
    name: 'Lisa Wang',
    email: 'lisa.wang@email.com',
    phone: '+1-555-0127',
    dateOfBirth: '1992-09-30',
  },
];

export const sampleProviders: Provider[] = [
  {
    id: 'provider-1',
    name: 'Dr. John Doe',
    specialization: 'Cardiology',
    email: 'john.doe@healthclinic.com',
  },
  {
    id: 'provider-2',
    name: 'Dr. Sarah Smith',
    specialization: 'Dermatology',
    email: 'sarah.smith@healthclinic.com',
  },
  {
    id: 'provider-3',
    name: 'Dr. Michael Brown',
    specialization: 'Orthopedics',
    email: 'michael.brown@healthclinic.com',
  },
  {
    id: 'provider-4',
    name: 'Dr. Jennifer Wilson',
    specialization: 'Pediatrics',
    email: 'jennifer.wilson@healthclinic.com',
  },
  {
    id: 'provider-5',
    name: 'Dr. Robert Davis',
    specialization: 'Neurology',
    email: 'robert.davis@healthclinic.com',
  },
];

export const sampleAppointments: Appointment[] = [
  {
    id: 'appointment-1',
    patientId: 'patient-1',
    providerId: 'provider-1',
    appointmentType: 'initial',
    location: 'In-Clinic',
    date: '2024-12-20',
    startTime: '10:00',
    endTime: '11:00',
    notes: 'Initial consultation for chest pain',
    status: 'Scheduled',
    isRecurring: false,
    createdAt: '2024-12-15T10:00:00Z',
    updatedAt: '2024-12-15T10:00:00Z',
  },
  {
    id: 'appointment-2',
    patientId: 'patient-2',
    providerId: 'provider-2',
    appointmentType: 'follow-up',
    location: 'Telehealth',
    date: '2024-12-21',
    startTime: '14:00',
    endTime: '14:30',
    notes: 'Follow-up on skin condition',
    status: 'Confirmed',
    isRecurring: true,
    recurrenceRule: 'weekly',
    createdAt: '2024-12-14T15:00:00Z',
    updatedAt: '2024-12-14T15:00:00Z',
  },
];

export const sampleAppointmentList: AppointmentListItem[] = [
  {
    id: 'apt-1',
    patientName: 'Heena West (F)',
    date: '2024-02-24',
    time: '11:17',
    type: 'New',
    providerName: 'Jacob Jones',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (65)',
    contactDetails: '202-555-0188',
    reasonForVisit: 'Infection Disease',
  },
  {
    id: 'apt-2',
    patientName: 'Arlene McCoy (M)',
    date: '2024-02-26',
    time: '21:40',
    type: 'Follow Up',
    providerName: 'Bessie Cooper',
    status: 'Confirmed',
    dateOfBirth: '10-21-1959 (42)',
    contactDetails: '202-555-0186',
    reasonForVisit: 'Itching',
  },
  {
    id: 'apt-3',
    patientName: 'Esther Howard (M)',
    date: '2024-03-07',
    time: '05:23',
    type: 'New',
    providerName: 'Wade Warren',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (32)',
    contactDetails: '202-555-0172',
    reasonForVisit: 'Insomnia',
  },
  {
    id: 'apt-4',
    patientName: 'Jane Cooper (F)',
    date: '2024-03-01',
    time: '06:05',
    type: 'Follow Up',
    providerName: 'Darrell Steward',
    status: 'Cancelled',
    dateOfBirth: '10-21-1959 (24)',
    contactDetails: '202-555-0124',
    reasonForVisit: 'Blurred Vision',
  },
  {
    id: 'apt-5',
    patientName: 'Darrell Steward (M)',
    date: '2024-03-10',
    time: '20:01',
    type: 'Follow Up',
    providerName: 'Savannah Nguyen',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (66)',
    contactDetails: '202-555-0198',
    reasonForVisit: 'Hearing Loss',
  },
  {
    id: 'apt-6',
    patientName: 'Esther Howard (F)',
    date: '2024-03-03',
    time: '10:48',
    type: 'New',
    providerName: 'Arlene McCoy',
    status: 'Confirmed',
    dateOfBirth: '10-21-1959 (12)',
    contactDetails: '202-555-0164',
    reasonForVisit: 'Headache',
  },
  {
    id: 'apt-7',
    patientName: 'Bessie Cooper (M)',
    date: '2024-02-26',
    time: '21:40',
    type: 'Follow Up',
    providerName: 'Darlene Robertson',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (32)',
    contactDetails: '202-555-0175',
    reasonForVisit: 'Stomach Pain',
  },
  {
    id: 'apt-8',
    patientName: 'Bessie Cooper (M)',
    date: '2024-03-03',
    time: '10:48',
    type: 'Follow Up',
    providerName: 'Bessie Cooper',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (42)',
    contactDetails: '202-555-0186',
    reasonForVisit: 'Itching',
  },
  {
    id: 'apt-9',
    patientName: 'Arlene McCoy (M)',
    date: '2024-02-24',
    time: '11:17',
    type: 'New',
    providerName: 'Wade Warren',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (32)',
    contactDetails: '202-555-0172',
    reasonForVisit: 'Insomnia',
  },
  {
    id: 'apt-10',
    patientName: 'Esther Howard (M)',
    date: '2024-03-08',
    time: '20:01',
    type: 'Follow Up',
    providerName: 'Darrell Steward',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (24)',
    contactDetails: '202-555-0123',
    reasonForVisit: 'Blurred Vision',
  },
  {
    id: 'apt-11',
    patientName: 'Jane Cooper (F)',
    date: '2024-03-10',
    time: '11:43',
    type: 'Follow Up',
    providerName: 'Savannah Nguyen',
    status: 'Confirmed',
    dateOfBirth: '10-21-1959 (66)',
    contactDetails: '202-555-0198',
    reasonForVisit: 'Hearing Loss',
  },
  {
    id: 'apt-12',
    patientName: 'Darrell Steward (M)',
    date: '2024-03-07',
    time: '12:27',
    type: 'New',
    providerName: 'Arlene McCoy',
    status: 'Scheduled',
    dateOfBirth: '10-21-1959 (12)',
    contactDetails: '202-555-0165',
    reasonForVisit: 'Headache',
  },
  {
    id: 'apt-13',
    patientName: 'Bessie Cooper (M)',
    date: '2024-03-05',
    time: '18:16',
    type: 'Follow Up',
    providerName: 'Robert Fox',
    status: 'Cancelled',
    dateOfBirth: '10-21-1959 (37)',
    contactDetails: '202-555-0119',
    reasonForVisit: 'Eye Redness',
  },
  {
    id: 'apt-14',
    patientName: 'Sarah Johnson',
    date: '2024-03-12',
    time: '09:30',
    type: 'New',
    providerName: 'Dr. John Doe',
    status: 'Scheduled',
    dateOfBirth: '1985-03-15 (39)',
    contactDetails: '202-555-0123',
    reasonForVisit: 'Annual Checkup',
  },
  {
    id: 'apt-15',
    patientName: 'Michael Chen',
    date: '2024-03-13',
    time: '14:15',
    type: 'Follow Up',
    providerName: 'Dr. Sarah Smith',
    status: 'Scheduled',
    dateOfBirth: '1990-07-22 (34)',
    contactDetails: '202-555-0124',
    reasonForVisit: 'Skin Condition',
  },
]; 